name: Golang API Server Test


on:
  push:
    branches:
      - "go-api-server/**"


defaults:
  run:
    working-directory: go_api_server


jobs:
  test:

    strategy:
      matrix:
        go-version: [1.19.x]  # [1.18.x, 1.19.x]
        os: [ubuntu-latest]   # [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install Dependencies
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.1

    - name: Run Lint
      run: |
        golangci-lint run -E gofmt -E stylecheck -E gocritic --verbose --out-format=github-actions

    - name: Run Unit Test
      run: |
        go test -v ./...
