name: Golang API Server Test


on:
  push:
    branches:
      - "**"
      - "!staging"
  pull_request:
    branches:
      - "**"
      - "!staging"


defaults:
  run:
    working-directory: golang_api_server


jobs:
  test:

    strategy:
      matrix:
        go-version: [1.19.x]  # [1.18.x, 1.19.x]
        os: [ubuntu-latest]   # [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install Dependencies
      run: |
        go version
        go install golang.org/x/lint/golint@latest

    - name: Run go vet
      run: |
        go vet ./...

    - name: Run Unit Test
      run: |
        go test -v ./...

    - name: Run golint
      run: |
        golint ./...

    - name: Run gofmt
      run: |
        go fmt ./...
